// This file is autogenerated. Changes will be overwritten.
#include <E4ZSR6OZTY/moc_ZegoDeviceManager.cpp>
#include <KRKR4BN5RM/moc_ZegoAudioView.cpp>
#include <KRKR4BN5RM/moc_ZegoLogLabel.cpp>
#include <KRKR4BN5RM/moc_ZegoMicrophoneButton.cpp>
#include <KRKR4BN5RM/moc_ZegoMircophone.cpp>
#include <KRKR4BN5RM/moc_ZegoProgressIndicator.cpp>
#include <KRKR4BN5RM/moc_ZegoTextButton.cpp>
#include <KRKR4BN5RM/moc_frameless_helper.cpp>
#include <M7I2D2MG4X/moc_ZegoAudioLiveDialog.cpp>
#include <M7I2D2MG4X/moc_ZegoMainDialog.cpp>
#include <M7I2D2MG4X/moc_ZegoSettingsDialog.cpp>
#include <TP6VRMQGQX/moc_NoFocusFrameDelegate.cpp>
#include <XX2LK5H2JO/moc_ZegoDialog.cpp>
#include <YQSYNMT4QO/moc_ZegoSDKSignal.cpp>
